services:
  mongodb:
    image: mongo:latest
    container_name: music_store
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    volumes:
      - music_store:/data/db

volumes:
  music_store: